### ISSUE TITLE
Camera app is crashing on Android 14 (latest beta)

### ISSUE THREAD

**Issue by empratyush** [GrapheneOS/Camera#369]
```
06-29 14:08:48.456 19392 19392 I PXLEXT_CameraXExtAdvancedExtender: Successfully initialized extension for Camera: 0
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: AdvancedExtenderImpl.getAvailableCaptureRequestKeys throws exceptions
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: java.lang.IllegalArgumentException: Could not find tag for key 'com.google.pixel.experimental2020.eisMode')
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.hardware.camera2.impl.CameraMetadataNative.nativeGetTagFromKeyLocal(Native Method)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.hardware.camera2.impl.CameraMetadataNative.getBase(CameraMetadataNative.java:596)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.hardware.camera2.impl.CameraMetadataNative.get(CameraMetadataNative.java:476)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.hardware.camera2.impl.CameraMetadataNative.get(CameraMetadataNative.java:459)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at androidx.camera.extensions.impl.advanced.CameraXExtAdvancedExtender.getAvailableCaptureRequestKeys(CameraXExtAdvancedExtender.java:157)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at androidx.camera.extensions.impl.advanced.AutoAdvancedExtenderImpl.getAvailableCaptureRequestKeys(AutoAdvancedExtenderImpl.java:97)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at i0.a.b(Unknown Source:18)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at i0.a.u(Unknown Source:15)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at androidx.camera.extensions.c.a(Unknown Source:59)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at androidx.camera.lifecycle.c.a(Unknown Source:428)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at u2.p.u(Unknown Source:866)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at u2.p.v(Unknown Source:236)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at app.grapheneos.camera.ui.activities.MainActivity.q(Unknown Source:43)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at u2.k.onTouch(Unknown Source:33)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.View.dispatchTouchEvent(View.java:15650)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4377)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at d.z.f(Unknown Source:2)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at d.z.dispatchTouchEvent(Unknown Source:0)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.View.dispatchPointerEvent(View.java:15918)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7025)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6823)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6237)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6294)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6260)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6425)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6268)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6482)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6241)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6294)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6260)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6268)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6241)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9215)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9166)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9135)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9341)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.os.MessageQueue.next(MessageQueue.java:335)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.os.Looper.loopOnce(Looper.java:162)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.os.Looper.loop(Looper.java:294)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at android.app.ActivityThread.main(ActivityThread.java:8176)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
06-29 14:08:48.457 19392 19392 E AdvancedVendorExtender: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
06-29 14:08:48.458 19392 19392 D CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
06-29 14:08:48.458 19392 19392 D CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
06-29 14:08:48.458 19392 19392 D DynamicRangeResolver: Resolved dynamic range for use case t.l1-11f77cf7-0fcb-4942-a773-eb95a385142a to no compatible HDR dynamic ranges.
06-29 14:08:48.458 19392 19392 D DynamicRangeResolver: DynamicRange@5f01449{encoding=UNSPECIFIED, bitDepth=0}
06-29 14:08:48.458 19392 19392 D DynamicRangeResolver: ->

```

**Comment by empratyush** [comment]
fixed in beta 5.1

**Comment by empratyush** [comment]
upstream issue  [#298297291](https://issuetracker.google.com/issues/298297291)

**Comment by empratyush** [comment]
fixed in newer pixel camera service.
